image: registry.gitlab.com/bitfireat/davdroid:latest

before_script:
  - git submodule update --init --recursive
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x gradlew
  - emulator64-arm -avd test -no-skin -no-audio -no-window & wait-for-emulator.sh

cache:
  paths:
     - .gradle/wrapper
     - .gradle/caches

test:
  script:
    - ./gradlew check mergeAndroidReports
  artifacts:
    paths:
      - app/build/outputs/lint-results-debug.html
      - app/build/reports
      - build/reports
