image: registry.gitlab.com/bitfireat/davdroid:latest

before_script:
  - git submodule update --init --recursive
  - export GRADLE_USER_HOME=`pwd`/.gradle; chmod +x gradlew
  - emulator64-x86 -avd test -no-audio -no-window & wait-for-emulator.sh
  - wget -q https://f-droid.org/repo/org.dmfs.tasks_481.apk && adb install org.dmfs.tasks_481.apk

cache:
  paths:
     - .gradle/

test:
  script:
    - ./gradlew check mergeAndroidReports
  artifacts:
    paths:
      - app/build/outputs/lint-results-debug.html
      - app/build/reports
      - build/reports
