image: registry.gitlab.com/bitfireat/davx5-ose:latest

before_script:
  - git submodule update --init --recursive
  - export GRADLE_USER_HOME=`pwd`/.gradle; chmod +x gradlew

cache:
  paths:
     - .gradle/

test:
  script:
#   - (cd /sdk/emulator; ./emulator @test -no-audio -no-window & wait-for-emulator.sh)
#   - ./gradlew check mergeAndroidReports
    - ./gradlew check
  artifacts:
    paths:
      - app/build/outputs/lint-results-debug.html
      - app/build/reports
      - build/reports

pages:
  script:
    - ./gradlew app:dokka
    - mkdir public && mv app/build/dokka public
  artifacts:
    paths:
      - public
  only:
    - master-ose
